spring:
  datasource:
    url: jdbc:mysql://localhost:3306/micro-credit?useUnicode=true&characterEncoding=utf8
    username: root
    password: root
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    filters: stat,wall,log4j
    maxActive: 20
    initialSize: 1
    maxWait: 60000
    minIdle: 1
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxOpenPreparedStatements: 20
    druid:
      filter:
        slf4j:
          enabled: true
          statement-create-after-log-enabled: false
          statement-close-after-log-enabled: false
          result-set-open-after-log-enabled: false
          result-set-close-after-log-enabled: false
  redis:
          host: 127.0.0.1
          port: 6379
          password:
          jedis:
            pool:
              max-active: 100
              max-idle: 10
              max-wait: 100000
          timeout: 0
 # mvc:
  # static-path-pattern: /static/**

#  thymeleaf:
#    prefix: classpath:/templates/
server:
  port: 8090
logging:
  config: classpath:logback-spring.xml

